version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "gftdcojp"
    assignees:
      - "gftdcojp"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "gftdcojp"
    assignees:
      - "gftdcojp"

  # Astro demo dependencies
  - package-ecosystem: "npm"
    directory: "/astoro"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "gftdcojp"
    assignees:
      - "gftdcojp"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
