[package]
name = "fukurow-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RESTful web API for Fukurow reasoning engine operations"
keywords = ["api", "rest", "web", "http", "reasoning"]
categories = ["web-programming", "api-bindings"]

[dependencies]
fukurow-core = "0.1.0"
fukurow-store = "0.1.0"
fukurow-engine = "0.1.0"
fukurow-domain-cyber = "0.1.0"
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
tower.workspace = true
async-trait = "0.1"
