[package]
name = "fukurow-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RESTful web API for Fukurow reasoning engine operations"
keywords = ["api", "rest", "web", "http", "reasoning"]
categories = ["web-programming", "api-bindings"]

[dependencies]
fukurow-core = { path = "../fukurow-core" }
fukurow-store = { path = "../fukurow-store" }
fukurow-engine = { path = "../fukurow-engine" }
fukurow-domain-cyber = { path = "../fukurow-domain-cyber" }
fukurow-observability = { path = "../fukurow-observability" }
axum.workspace = true
tower = { workspace = true, features = ["make"] }
tower-http.workspace = true
hyper = "1.0"
hyper-util = { version = "0.1", features = ["tokio"] }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
async-trait = "0.1"

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
tower.workspace = true
async-trait = "0.1"
