[workspace]
members = [
    "crates/fukurow-core",
    "crates/fukurow-store",
    "crates/fukurow-rules",
    "crates/fukurow-engine",
    "crates/fukurow-domain-cyber",
    "crates/fukurow-api",
    "crates/fukurow-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["gftdcojp"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/gftdcojp/fukurow"

[profile.release]
# LTO (Link Time Optimization) - 最適化されたバイナリ生成
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3

[profile.release.package.fukurow-engine]
# エンジンcrateの特別最適化
opt-level = "z"  # サイズ最適化優先
lto = true

[profile.release.package.fukurow-store]
# ストアクrateの特別最適化
opt-level = "s"  # サイズと速度のバランス

# WebAssembly specific configurations
[target.wasm32-unknown-unknown.dependencies]
# WASM固有の依存関係（必要に応じて）
getrandom = { version = "0.2", features = ["js"] }
chrono = { version = "0.4", features = ["wasmbind"] }

# WASMビルド時の機能フラグ
[features]
default = ["console_error_panic_hook"]
console_error_panic_hook = ["dep:console_error_panic_hook"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"

[workspace.dependencies]
# Core dependencies shared across crates
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# JSON-LD and RDF processing
json-ld = "0.16"
sophia = { version = "0.8", features = ["jsonld", "xml"] }

# Web framework
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Testing
proptest = "1.0"

# Async traits
async-trait = "0.1"

# WebAssembly support
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
js-sys = "0.3"
