[package]
name = "fukurow-store"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RDF triple store with provenance tracking and audit trails for Fukurow"
keywords = ["rdf", "triple-store", "provenance", "audit", "knowledge-graph"]
categories = ["database", "data-structures"]

[dependencies]
fukurow-core = { path = "../fukurow-core" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
