[package]
name = "reasoner-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reasoner-graph = { path = "../graph" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
