[package]
name = "fukurow-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
sophia.workspace = true
json-ld.workspace = true
iri-string = "0.7"
uuid = { version = "1.0", features = ["v4", "serde", "js"] }
wasm-bindgen = { workspace = true, optional = true }

[features]
default = []
wasm-bindgen = ["dep:wasm-bindgen", "uuid/js", "getrandom/js"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
