[package]
name = "fukurow-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Reasoning engine orchestration that integrates reasoners and rules for Fukurow"
keywords = ["reasoning", "inference", "engine", "orchestration", "knowledge-graph"]
categories = ["algorithms", "concurrency"]

[dependencies]
fukurow-core = "0.1.0"
fukurow-store = "0.1.0"
fukurow-rules = "0.1.0"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
async-trait.workspace = true
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
